### ISSUE TITLE
Bug Groupe 6 - Recettage

### ISSUE THREAD

**Issue by AylineT** [nuit-musee-musba/experience#128]
<img width="1470" alt="Capture d’écran 2024-02-09 à 10 26 45" src="https://github.com/nuit-musee-musba/experience/assets/99130296/03c54005-686f-4b12-834e-564c6e8d8389">

superposition des infos dans le livre quand on a pas sélectionné d'objet avant de drag and drop

**Comment by presqueasmr** [comment]
SCENE INTRO

- [ ] Blur trop fort 

Dialogue 1 / 6
- [ ] Modifier texte : "Oh ! Quelle aubaine, vous tombez à pic(asso) !
- [ ] Sauter une ligne après "picasso"
- [ ] Mettre en gras : "Jan Brueghel de Velours"

**Comment by AylineT** [comment]
Quand c'est un ingrédient à mettre plus tard changer le texte par : "Mmh, gardez-le sous votre établi, il nous sera peut-être utile plus tard."

**Comment by AylineT** [comment]
Texte de début "aidez vous de l'encyclopédie "liconologia" : enlever l'icolonogia

**Comment by AylineT** [comment]
Changer le texte du poisson en "Il représente Jésus-Christ mais aussi le baptême car “tout comme le poisson ne peut pas vivre sans eau, le croyant ne peut pas être chrétien sans baptême” (sacrement réalisé avec de l’eau)."

**Comment by AylineT** [comment]
<img width="1049" alt="image" src="https://github.com/nuit-musee-musba/experience/assets/99130296/b7c2dba4-1ea0-4285-ba6e-2e3032e51d02">

Les ingrédients passent au dessus de tous les éléments sauf la liste, est ce que c'est volontaire ?

**Comment by AylineT** [comment]
https://github.com/nuit-musee-musba/experience/assets/99130296/54e12516-cd18-4266-92af-d7ac27a3345d

Jeff disparait furtivement entre chaque anim, je sais pas si c'est fixable mais ça serait cool !

**Comment by AylineT** [comment]
- [ ] Padding du dialogue trop petit changer en : 46px en X  et 53px en Y

**Comment by presqueasmr** [comment]
Bug 
- [ ] La liste ne s'update pas (la liste 1 ne passe pas à la liste 2 si tous les éléments sont mis) si on met trop de temps à mettre les ingrédients sur la table 

Modification esthétique
- [ ] ne pas barrer l'icône quand l'ingrédient est validé dans la liste : 
![Capture d'écran 2024-02-09 114339](https://github.com/nuit-musee-musba/experience/assets/95074113/01dfffd9-8325-4f47-8712-64b812476741)

**Comment by presqueasmr** [comment]
Feature à rajouter : 
-[ ] Griser les ingrédients validés

**Comment by AylineT** [comment]
- [ ] les 3 ont des font différentes ? 
<img width="151" alt="image" src="https://github.com/nuit-musee-musba/experience/assets/99130296/31c5cd1e-bc7f-478f-b3f6-723a1ea775ba">

**Comment by presqueasmr** [comment]
Reformulation boîte dialogue d'erreur : 
- [ ] "Vous en avez assez mis" changer en --> "Vous en avez déjà mis cet élément" ou "Vous en avez déjà mis un"

**Comment by presqueasmr** [comment]
Reformulation boîte dialogue d'erreur : 
- [ ] "Vous en avez assez mis" changer en --> "Vous en avez déjà mis cet élément" ou "Vous en avez déjà mis un"

**Comment by AylineT** [comment]
- [ ] rajouter la musique

**Comment by 97Lucaas** [comment]
> Bug
> 
> * [ ]  La liste ne s'update pas (la liste 1 ne passe pas à la liste 2 si tous les éléments sont mis) si on met trop de temps à mettre les ingrédients sur la table

je n'ai pas pu reproduire le bug

**Comment by presqueasmr** [comment]
Info livre recette : 
- [ ] "Il est symbole de fidélité en amour. Il désigne également la divinité, la foi et l’Église. Le citronnier étant l’allégorie du cèdre, le citron peut alors représenter Jésus-Christ car sa croix est faite de bois de cèdre." CHANGER EN --> Il est symbole de <b>fidélité en amour</b>. Dans les vanités, le citronnier est également associé au cèdre ; bois dans lequel était conçue la croix de Jésus Christ. Le citron peut donc symboliser <b>le Christ, la foi et l’Église</b>.

**Comment by presqueasmr** [comment]
Transition fin : 
la dernière scène s'affiche avant la transition "ding"

**Comment by presqueasmr** [comment]
SCENE FINALE : Changement contenu dernière bulle dialogue

Toutes mes félicitations ! Vous venez de réaliser votre première vanité sous mon œil d’expert. Et si nous l’appelions “Nature morte aux crustacés” ! L’artiste en vous est en train de naître, peut-être qu’un jour vous dépasserez le maître ! Jan Brueghel de Velours ne pourra que l’adorer !

**Comment by AylineT** [comment]
- [ ] @97Lucaas Le style des boutons du tuto ça serait bien qu'ils collent à l'UI globale
