### ISSUE TITLE
Probleme / résultat des tests 

### ISSUE THREAD

**Issue by bastiengrn** [nuit-musee-musba/experience#42]
- [x] Uniformiser les taille de police avec toutes les expériences
- [x] zoom à désactiver

**Comment by Olivia206** [comment]
@bastiengrn on peut avoir un screen de l'image en question stp ?

**Comment by bastiengrn** [comment]
Je viens de tester sur le Pc ça ne le fait pas, mais ce matin vos images ne s'affichait pas correctement sur la tablette,  malheureusement, je n'ai pas pris de screen. Je ne sais si @97Lucaas vois de quoi je parle ?

**Comment by arthaud-proust** [comment]
Vu avec Olivia : c'est normale que les images ne chargent pas, elles ne les ont pas encore créé
Du coup c'est pas vraiment un bug, je l'ai enlevé
